### ISSUE TITLE
error adding format 320: no control named 'file_input'

### ISSUE THREAD

**Issue by tordenflesk** [MattRob1nson/REDBetter#1]
Config:
```
[redacted]
username = ***
password = ***
data_dir = /mnt/hgfs/Finished/RED
output_dir = /mnt/hgfs/Incoming
torrent_dir = /mnt/hgfs/Load/
formats = flac, 320
media = sacd, soundboard, web, dvd, cd, dat, vinyl, blu-ray
24bit_behaviour = 0
piece_length = 18

```

**Comment by MattRob1nson** [comment]
A couple of things:

- Do you have the mechanize, mutagen, requests and Unidecode Python modules installed? "no control named" sounds like something from mechanize.
- Have you added the IP belonging to the network from which you are running REDBetter to the VPN whitelist on your profile?
- What is your environment? OS, Python version etc.

**Comment by tordenflesk** [comment]
[Modules](https://i.imgur.com/y4AbJiV.png)
Ubuntu Server 18.10 VM, Python 2.7

**Comment by MattRob1nson** [comment]
Could you please show the full output containing "error adding format 320: no control named 'file_input'"?

**Comment by tordenflesk** [comment]
Not much to show:
https://i.imgur.com/4TB0hqN.png

**Comment by tordenflesk** [comment]
Oh, I'm sorry. Apparently my upload privileges have been revoked.... That would most likely be the issue. :(
